### PR TITLE
working DistilBERT example with notebook

### PR DESCRIPTION
**Pull request by dhalf**
Working DistilBERT fine tuning example with DP-SGD (on the SMS Spam Collection) and accompanying notebook

### CODE REVIEW

**Review by kbamponsem — COMMENTED** [review]
Nice LICENSE file.
I want to ask why you want to use a Makefile instead of  `setup.py` and add all the necessary build steps.

Just like it is now?

Also, I noticed you added an examples directory under client.

How about putting the bert in the root of the project, adding it unto `SampleLinearRegression.ipynb`?

**Comment by kbamponsem** [comment]
Also, regarding the notebook, ideally, you would want the user to install from **Pypi** right?
So, instead of 
```shell
cd bastionai/client && make install
```

you would want to do 
```shell
! pip install bastionai
```
Exactly why not having a Makefile is a good idea, and it simplifies installing the package.
Once you have a `setup.py` file, it setups up all the necessary configuration when you run `pip install bastionai`

**Comment by dhalf** [comment]
> Nice LICENSE file. I want to ask why you want to use a Makefile instead of `setup.py` and add all the necessary build steps.
> Just like it is now?

So, I think the new standard to build python packages is to use setup.cfg + pyproject.toml instead of a raw setup.py, that's why I moved around some of the build configs
The Makefile is a good way to reproduce the dev environement and to ease building by writting all the steps at the same place. It is widely used, installed on all Linux platforms, easy to understand and adapt.

> Also, I noticed you added an examples directory under client.
> 
> How about putting the bert in the root of the project, adding it unto `SampleTraining.ipynb`?

That's actually a good idea, I also think that all current files under tests and examples should be moved to the root as they use both the client and the server. We can them make unit tests for each component

**Comment by dhalf** [comment]
> Also, regarding the notebook, ideally, you would want the user to install from **Pypi** right? So, instead of
> 
> ```shell
> cd bastionai/client && make install
> ```
> 
> you would want to do
> 
> ```shell
> ! pip install bastionai
> ```
> 
> Exactly why not having a Makefile is a good idea, and it simplifies installing the package. Once you have a `setup.py` file, it setups up all the necessary configurations when you run `pip install bastionai
> 
> And for the extra pip packages needed in the notebook, I believe you can easily install them in the notebook by running
> 
> ```shell
> ! pip install transformers pandas sklearn ipykernel ipywidgets
> ```

This is a very good point
I'll fix the notebook and conform to the ! syntax

Regarding the bastionai pip package, it is not ready yet so I would jut include the two installation schemes (package manager + from source)

**Pull request merged**
